#!/usr/bin/env php
<?php

if (file_exists(__DIR__.'/../../autoload.php')) {
    require __DIR__.'/../../autoload.php';
} else {
    require __DIR__.'/vendor/autoload.php';
}

use Liquidpineapple\Ranch\Commands\AddCommand;
use Liquidpineapple\Ranch\Commands\InitCommand;
use Liquidpineapple\Ranch\Commands\SitesCommand;
use Liquidpineapple\Ranch\Commands\ValidateCommand;
use Symfony\Component\Console\Application;

$application = new Application('Ranch – Easy homestead site management');
$application->add(new AddCommand);
$application->add(new InitCommand);
$application->add(new SitesCommand);
$application->add(new ValidateCommand);
$application->run();
